### PR TITLE
Added castling features

### PR DESCRIPTION
**Pull request by jake-lonceras**

### CODE REVIEW

**Comment by jake-lonceras** [comment]
added initial movement for the king object. then set those initial movement as preffered one when the king is on it's initial pos

**Comment by jake-lonceras** [comment]
@23nith pa test if nag wowork siya thanks.

**Comment by 23nith** [comment]
Nice gumagana siya, siguro need nalang ng further tweaking kasi nagana siya kahit may pieces in between. Sa panibagong branch  nalang siguro yun. Go na for merging. lgtm.

**Comment by 23nith** [comment]
@jake-lonceras

**Review by 23nith — APPROVED** [review]
Nice gumagana siya, siguro need nalang ng further tweaking kasi nagana siya kahit may pieces in between. Sa panibagong branch nalang siguro yun. Go na for merging. lgtm. @jake-lonceras

**Comment by 23nith** [comment]
Ay gumagana din pala siya pag wala yung rook... needs tweaking pa pala...

**Pull request merged**
