### PR TITLE
Feat/checkmate

### PR DESCRIPTION
**Pull request by 23nith**
The only thing missing is having the ability to recognize if a capture move can be countered or blocked by king's ally pieces. (see third photo). 
Worked in this scenario (checkmate black king)
image
Worked in this scenario (checkmate white king)
image

@jake-lonceras You may add to this code if you want.. this is the remaining flaw that I have yet to find a way to translate to code efficiently... I'm thinking I might have to loop thru the other pieces to take into account each of the other piece's possible moves then run the same checkmate code again within its code block (recursion).. but then I haven't refactored the code yet (not even sure if I could) and that would make the code even more confusing. 
 
image

### CODE REVIEW

**Comment by 23nith** [comment]
@jake-lonceras next step siguro is kung pano irefactor yung checkmate code para magawa yung recursion... kung hindi kasi, magiging nakakalito... baka hindi kayanin ng Saturday itong feat.. need more time for this feat to work properly.. pero overall ito nalang kulang natin..

**Comment by 23nith** [comment]
@jake-lonceras Gawa na, no more problems..., at least on my end. Feel free to stress test this thanks!
image

**Comment by 23nith** [comment]
@jake-lonceras Pacheck ulit.. thanks sa paghanap last time ng flaw..
image

**Review by jake-lonceras — CHANGES_REQUESTED** [review]
image

image

**Comment by 23nith** [comment]
@jake-lonceras  already made some changes pareview ulit thanks!

**Comment by 23nith** [comment]
@jake-lonceras This time tinatake into account na kung pwede makain yung mga threats

**Comment by 23nith** [comment]
@jake-lonceras I made two revisions wala na yung problem dun sa parehas na photos

**Comment by 23nith** [comment]
@jake-lonceras Paclone ng bago para sure na nadagdag yung dalawang newest revisions, thanks

**Comment by 23nith** [comment]
@jake-lonceras Here's the FEN para mareplicate yung unang photo sa taas:
rnb1kbnr/pppp1ppp/8/4p2q/5PP1/8/PPPPP2P/RNBQKBNR move Queen from H5 to H3
Capture12


Ito naman yung FEN sa pangalawang photo
r1bqkbnr/pp2pppp/3pQ3/2p5/2P5/8/PP1PPPPP/RNB1KBNR move Queen from E6 to D7
Capture11

**Review by jake-lonceras — CHANGES_REQUESTED** [review]
image

**Comment by 23nith** [comment]
@jake-lonceras Pasuyo ulit for review.. thank you
rnbqkbnr/ppppp2p/8/5pp1/4P2Q/P7/1PPP1PPP/RNB1KBNR   move queen from H4 to H5


rnbqkbnr/1ppp1ppp/p7/4p2q/5PP1/8/PPPPP2P/RNB1KBNR move queen from H4 to H3

**Comment by 23nith** [comment]
ay di ko pa pala napupush

**Comment by 23nith** [comment]
@jake-lonceras ayan napush ko na

**Comment by 23nith** [comment]
ay wait.. may mali..

**Comment by 23nith** [comment]
@jake-lonceras for your review

**Comment by 23nith** [comment]
@jake-lonceras for your review.. may bug ako nakita pero nafix na

**Comment by 23nith** [comment]
@jake-lonceras for your review., dinouble check ko narin para sure

**Comment by 23nith** [comment]
@jake-lonceras tinatake into account na ng code kung pwede icounter capture si king
rnbqkbnr/2ppp2p/5Q2/pp4N1/8/4P3/PPPP1PPP/RNB1KB1R <------------ move Queen from F6 to F7  (scenario 1)
image

**Comment by 23nith** [comment]
@jake-lonceras ginawa ko na palang image yung background para kahit maghighlight kita parin yung checkered sa ilalim

**Review by jake-lonceras — CHANGES_REQUESTED** [review]
image

**Comment by 23nith** [comment]
@jake-lonceras patest ulit. Don't worry dinouble check ko rin muna bago iPR. Feel free to stress test again. Thank you so much

**Comment by 23nith** [comment]
Mukha na siyang legit na chess game
image

**Review by jake-lonceras — CHANGES_REQUESTED** [review]
image

**Comment by 23nith** [comment]
@jake-lonceras ito promise last na .. yung object ko pala na pinagstostoran ng values hindi tama., finix ko na

**Review by jake-lonceras — CHANGES_REQUESTED** [review]
image

**Comment by jake-lonceras** [comment]
@23nith 
image

**Comment by jake-lonceras** [comment]
@23nith 
image

**Comment by 23nith** [comment]
> 

pwede pala kainin ng rook si queen

**Comment by 23nith** [comment]
@jake-lonceras commited fixes see images below

r1bk2nr/2pqpQ2/1pn2p1p/p5p1/P7/2PR4/1P1PPPPP/1NB1KBNR move Queen from F7 to F8
image

rnb2k1r/pppRppb1/6p1/7p/P3nPP1/8/1PPPP2P/1NBQKBKR move Rook from D7 to D8
image

**Review by jake-lonceras — CHANGES_REQUESTED** [review]
ganon padin ? Fen ba ginamit mo @23nith ? 
in game to ginawa ko ganon padin result.
image

different scenario
image

kaunting tweak nalang to, bka di lang nakonsider if pwede siya i block
image

**Comment by 23nith** [comment]
@jake-lonceras meron palang nag undefined na variable kaya hindi dumiretso sa checkmate condidtion
natry ko narin siya ng live kanina .., nireproduce ko lang ng fen para sa photo
image

image

**Comment by 23nith** [comment]
ay wait di ko pa napush

**Comment by 23nith** [comment]
@jake-lonceras ayan napush na

**Review by jake-lonceras — CHANGES_REQUESTED** [review]
ganon padin? bkaa hindi mo pa ata siya na pupush ? nag clone na ako bago.
image

new scenario dito instead queen pam block yung bishop naman
image

**Comment by 23nith** [comment]
Bakit sakin okay naman..
image

pero yung pangalawang photo .. yun yung kailangan ayusin

**Comment by 23nith** [comment]
@jake-lonceras patest ulit, thanks.. 
image

image

**Review by jake-lonceras — CHANGES_REQUESTED** [review]
goods na sa part na to but 
image

Pag hinarang si queen then capture ni rook checkmate nakalgay see image below
image

**Comment by 23nith** [comment]
Okay naexclude ko pala sa condition kung can be captured ni king
image

**Review by jake-lonceras — CHANGES_REQUESTED** [review]
image

**Comment by 23nith** [comment]
@jake-lonceras Yung "if(threatsOnKing == canBeCaptured) return; " pala dapat "if(threatsOnKing <= canBeCaptured) return;"
image

**Review by jake-lonceras — CHANGES_REQUESTED** [review]
image

**Comment by 23nith** [comment]
@jake-lonceras dapat pala deduct ko lang siya sa canbecaptured pag king yung nagcapture 

image


image

**Review by jake-lonceras — CHANGES_REQUESTED** [review]
image

**Comment by 23nith** [comment]
@jake-lonceras dapat pala hindi ko ibreak yung loop para lahat ng ally pieces ni king macheck kung pwede magblock

image

image

**Review by jake-lonceras — CHANGES_REQUESTED** [review]
nag chain nanamn ata.
nas solve mo na to dati alam ko.
image

**Comment by jake-lonceras** [comment]
image

image

**Comment by jake-lonceras** [comment]
open check capture naman . last kasi harang lang.
image

**Comment by 23nith** [comment]
@jake-lonceras hmm... dahil yata dito ginawa ko kasi kaninang "<=".., nakakalito
image

**Comment by 23nith** [comment]
@jake-lonceras malakas pakiramdam ko wala na 'tong flaw.. hopefully... sobrang tinriple double check ko na siya
image

**Review by jake-lonceras — CHANGES_REQUESTED** [review]
yung ibang scenario ng checkmate sa white di applicable sa black
e.g
image

**Comment by jake-lonceras** [comment]
nag chain nanaman.

image

**Comment by 23nith** [comment]
@jake-lonceras sige double check ko yung sa white.., don't worry hindi nagchain yung sa last part. Kasi nagfalse yan sa allMovesCheck tapos nag true dun sa piece na may direct line of sight kay king at another "safe tile" sa likod ni king.. hindi ko pa nadagdagan if canBeCaptured at canBeBlocked na condition pala yun.

**Comment by 23nith** [comment]
@jake-lonceras sige ayusin ko yung sa white.. nga pala yung huling photo na sabi mo nagchain.. sakin hindi siya nagchecheckmate... 

check mo nga ito kung same scenario nga siya.. kailangan ko kasi ireplicate para madebug
image

kahit dito hindi ako nagfen , live game to.. tama naman
image

**Comment by 23nith** [comment]
@jake-lonceras okay na., finix ko bug dun sa for checking ng checkmate kay white king., Tapos sa yung issue din na huli 

image

**Comment by 23nith** [comment]
@jake-lonceras for your review., dinouble check ko na to promise.. feeling ko wala nang problem.. sana

**Comment by 23nith** [comment]
Scenarios that passed the test:
image
image
image

**Comment by 23nith** [comment]
Ay wait

**Comment by 23nith** [comment]
@jake-lonceras for your review okay na

**Review by jake-lonceras — CHANGES_REQUESTED** [review]
Chained na naman siya.

image

**Comment by 23nith** [comment]
@jake-lonceras  bakit sakin hindi nangyayari
image

**Comment by 23nith** [comment]
@jake-lonceras okay na. Nakita ko na san yung problem. finix ko na
image

**Comment by 23nith** [comment]
@jake-lonceras last na sorry.., nafix ko na ulit
image

**Review by jake-lonceras — CHANGES_REQUESTED** [review]
1R2krn1/3rqp2/1b1p2p1/nQp5/7p/2P1R2P/pP1PPP2/1NB1KBN1

image

**Comment by 23nith** [comment]
@jake-lonceras di ko mareplicate., sakin iba
image

**Comment by 23nith** [comment]
@jake-lonceras nasolve na yung sa pagbilang ng pieces in between king and threat.. for your review ulit

**Review by jake-lonceras — CHANGES_REQUESTED** [review]
Nice.

**Review by jake-lonceras — APPROVED** [review]
NIce

**Pull request merged**
