### PR TITLE
Fix/castling when piece in between

### PR DESCRIPTION
**Pull request by jake-lonceras**

### CODE REVIEW

**Comment by jake-lonceras** [comment]
@23nith Fix yung sa White plang. 
image

**Comment by jake-lonceras** [comment]
@23nith yung sa left side  din kapag nag move ng isa. 
image

**Comment by jake-lonceras** [comment]
@23nith For Black fix, yung sa left and right side if ng move ng one. 
image
image

**Comment by jake-lonceras** [comment]
@23nith Pa test ulit if yung bugs still persist. or my result na new bugs. Thanks..

**Comment by jake-lonceras** [comment]
Queen size fix.
image

**Comment by jake-lonceras** [comment]
Black Queen side fix.
image

**Comment by 23nith** [comment]
Okay na, already tested, nawala na yung bug good for merging na to @jake-lonceras

**Review by 23nith — APPROVED** [review]
Okay na, already tested, nawala na yung bug good for merging na to @jake-lonceras

**Pull request merged**
