### PR TITLE
Fix castling issues on both white and black if there are pieces between and on it's highlighting.

### PR DESCRIPTION
**Pull request by jake-lonceras**

### CODE REVIEW

**Comment by jake-lonceras** [comment]
@23nith pa test if yung issues na sinolve is existing parin, thanks. will work on pawn promotion bugs next. thanks

**Comment by 23nith** [comment]
Pag kinopy paste tong FEN na to hindi nangyayari yung issue. Pero pag nireplicate mo ng live game tapos inusog mo si white king sa left may wierd na nangyayari.. (pls see screen shot
Capture5
)

**Review by 23nith — CHANGES_REQUESTED** [review]
Pag kinopy paste tong FEN na to (rnbqkbnr/p1p3pp/1p1p1p2/4p3/1PPP4/1Q2P3/P4PPP/RNB1KBNR) hindi nangyayari yung issue. Pero pag nireplicate mo ng live game tapos inusog mo si white king sa left may wierd na nangyayari.. (pls see screen shot)
Capture5

**Comment by jake-lonceras** [comment]
> Pag kinopy paste tong FEN na to (rnbqkbnr/p1p3pp/1p1p1p2/4p3/1PPP4/1Q2P3/P4PPP/RNB1KBNR) hindi nangyayari yung issue. Pero pag nireplicate mo ng live game tapos inusog mo si white king sa left may wierd na nangyayari.. (pls see screen shot) Capture5

**Comment by jake-lonceras** [comment]
@23nith  pa list nung bug sa notea, fix ko to bago yung bugs sa promotion. Thanks.

**Pull request closed without merging**
