### PR TITLE
Fix promotion bug opponent piece can move on promotion process.

### PR DESCRIPTION
**Pull request by jake-lonceras**

### CODE REVIEW

**Review by 23nith — CHANGES_REQUESTED** [review]
@jake-lonceras nawawala pala yung ability ni opponent iblock yung attempt mo na mag promote ng pawn piece as shown below (screenshot)
Capture6
 So dapat highlighted yung area kung saan mapopromote si pawn. Para iprevent ni black si white na magpromote.

**Comment by jake-lonceras** [comment]
@23nith draft plng to zen.

**Comment by 23nith** [comment]
image

**Comment by 23nith** [comment]
image

**Comment by 23nith** [comment]
@jake-lonceras Okay na to kasi nafix siya nung inapply kong fix para dun sa bug ng en passant.. kung baga yun din yung fix para sa "highlighting sometimes not working" na bug.

**Comment by 23nith** [comment]
@jake-lonceras ito yung solution dito sa bug (please see screenshot) burahin mo lang yung mga nakaencircle.
image5

**Review by 23nith — APPROVED** [review]

**Pull request merged**
