### PR TITLE
Added promotion feature

### PR DESCRIPTION
**Pull request by jake-lonceras**

### CODE REVIEW

**Comment by jake-lonceras** [comment]
@23nith pa check working yung feature, thanks

**Comment by 23nith** [comment]
@jake-lonceras quick question lang.. Nung pinull mo ba to wala pa yung en passant? hindi ba mabubura yung en passant pag minerge to? may niresolve ka bang conflict?

**Comment by 23nith** [comment]
Just making sure.. pero tinest ko gumagana nga yung promotion nice!

**Comment by 23nith** [comment]
@jake-lonceras Ah never mind.. pag niresolve mo nalang make sure not to delete en passant... sa resolve conflicts pala makikita yung en passant kasi hindi pa siya namemerge nung ginawa tong branch

**Comment by jake-lonceras** [comment]
> @jake-lonceras quick question lang.. Nung pinull mo ba to wala pa yung en passant? hindi ba mabubura yung en passant pag minerge to? may niresolve ka bang conflict?

Wala, hindi

**Pull request merged**
